---
- name: start httpd service if it is not running
  hosts: all
  become: yes
  tasks:
    - name: check httpd service and start it
      shell: ps -ef| grep -v grep| grep -i httpd
      changed_when: false
      register: output
      ignore_errors: true
    - name: start httpd service if not running
      service:
        name: httpd
        state: started
      when: output.rc == 1
    - name: display the output if already running
      debug:
        msg: " httpd is already running "
      when: output.rc == 0

